# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-02 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('thoughts', '0002_auto_20180302_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thought',
            name='recorded_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
